---
title: "Social Capital"
author: "Jackson Roe"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(stringr)
```



```{r}
ec <- read_rds("ec.rds")
```

```{r}
# my county
# ec |> 
 # filter(county_name == "Franklin, Ohio")
```


```{r}
# could do x = log(x = pop2018)
ec |> 
  drop_na() |> 
  ggplot(aes(x = pop2018, y = ec_county)) +
    geom_point() +
    geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
    scale_x_log10() + 
    labs(title = "Economic Connectedness (EC) of US Counties, by Population", 
         subtitle = "No correlation between population and EC", 
         x = "Population", 
         y = "EC Score")
```
```{r}
ec |>
  drop_na() |>
  mutate(state = str_remove(county_name, ".*, ")) |> 
  group_by(state) |>
  summarize(pop_state = sum(pop2018), 
            avg_ec = mean(ec_county)) |>
  ggplot(aes(x = pop_state, y = avg_ec)) +
    geom_point() + 
    geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
    scale_x_log10(breaks = c(1000, 10000, 1000000), 
                  labels = c("1,000", "10,000", "1,000,000")) + 
    labs(title = "Economic Connectedness and Population in US Counties",
         subtitle = "Bigger states have counties with lower average economic connectedness",
         x = "Population",
         y = "Economic Connectedness")

```


```{r clean_data}
x <- ec |> 
  mutate(state = str_remove(county_name, ".*, "))

```



